### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by RvdBovenkamp** [piotrjurkiewicz/flow-models#1]
A type cast to int is done in a few places:

plot.py line 39
lib\plot.py lines 110,171,188

Usually in the form of 
idx = np.unique(np.rint(np.geomspace(data.index.min(), data.index.max(), LINE_NBINS)).astype(int))

These can result in overflows (as is the case when using the histogram data from agh_2015). A change to astype(numpy.int64) solves this.

**Comment by piotrjurkiewicz** [comment]
This was problem only on Windows, as on 64-bit Linux systems `astype(int)` is equivalent to `astype(numpy.int64)`.

Thank you for the report, fixed.
